### ISSUE TITLE
I have a problem about this interface

### ISSUE THREAD

**Issue by ThomasJin** [korvin011/ADS-Matlab-Interface#5]
When i am using this interface, i find a problem about Function (Run simulation) :
Java exception occurred:
java.io.IOException: Cannot run program "hpeesofsim" (in directory
"C:\Users\13358\Desktop\korvin011-ADS-Matlab-Interface-8327d13\Demos\ADSProjects\MSFilter_2ParamSweep_wrk"): CreateProcess error=2, The system cannot find the specified file.

	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)

Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the specified file.

	at java.lang.ProcessImpl.create(Native Method)

	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)

	at java.lang.ProcessImpl.start(ProcessImpl.java:137)

	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)

error  TADSInterface/RunSimulation (line 2071)
                    ExitCode = TADSInterface.RunProcessAsync('hpeesofsim', {['"' NetlistName NetlistExt '"']}, NetlistPath, @ProcessOutputLine);

error Untitled (line 32)
    ADS.RunSimulation();

Can you give me some advice about this?
Thank you!

**Comment by korvin011** [comment]
Hi,
It seems tha PATH is not set corretly. Please see also [this issue](https://github.com/korvin011/ADS-Matlab-Interface/issues/2)
